[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
sepolia = "https://sepolia.infura.io/v3/e4f95bf3b00845abbd6ff6c47fe23e91"

[remappings]
remappings = ["forge-std/=lib/forge-std/src/", "@openzeppelin/=lib/openzeppelin-contracts/contracts/"]
